    <!-- Commande Valider -->
     <section class="flex flex-col gap-4 w-full h-fit">

        <div class="flex bg-ligth-gray justify-center items-center w-full h-14 py-2">
            <p class="text-lg font-normal">Commande Valider</p>
        </div>

        <div class="flex flex-col gap-8 items-center my-24">
            <h2 class="font-bold text-xl">Thank you for your purchase !</h2>
            <div class="flex flex-row justify-evenly items-center w-25rem h-fit p-2 gap-5">
                <button id="return"class="bg-black text-white w-full h-10">Return to home page</button>
            </div>
        </div>

     </section>