<div class="flex flex-col min-w-20rem min-h-20rem w-25rem h-25rem border-2 overflow-hidden relative group">
  <img class="w-full h-full object-cover transition-transform duration-300 ease-in-out group-hover:scale-125" src="{{url}}"
    alt="image de {{name}}" loading="lazy">
</div>
<div class=" flex flex-row justify-evenly items-center w-25rem h-fit p-2 gap-5">
    <label class="font-medium">{{name}}</label>
    <select id="select" class="w-full h-10 border-gray border-2">
    </select>
</div>

