
    <article id="card" data-id="{{id}}" class="flex flex-col gap-4 w-25rem h-full max-h-30rem m-4 items-stretch cursor-pointer" data-id="{{id}}">
        <div class="w-full h-25rem flex items-center justify-center bg-cover overflow-hidden" data-id="{{id}}">
            <img class="" src="{{image}}" alt="Image du produit : {{name}}" data-id="{{id}}">
        </div>
    
        <div class="flex flex-row justify-between" data-id="{{id}}">
            <p data-id="{{id}}" class="font-bold text-lg">£ {{price}}</p>
            <img class="w-6 h-6" src="../assets/heart.png" data-id="{{id}}">
        </div>

        <p class="w-full h-12 overflow-hidden" data-id="{{id}}">{{name}}</p>
    </article>