    <!-- TEMPLATE CONFIRMATION COMPTE -->
    <section class="flex flex-col items-center w-full h-fit gap-40 align-middle">

        <div class="flex bg-ligth-gray justify-between items-center w-full h-14 py-2">
            <div class="flex justify-center items-center w-6 h-6 ml-8">
                <img class="w-full h-full object-contain" src="../assets/arrow-left.svg" alt="Arrow Left">
            </div>
            <p class="text-sm font-normal">Confirm</p>
            <div class="w-16 h-16"></div>
        </div>

        <form id="login" class="flex flex-col gap-4 w-25rem h-fit">

            <div class="flex flex-col w-25rem h-fit">
                <p class="text-xs text-gray">Please enter your Password</p>
                <input name="password" class="border-2 border-gray p-2" type="password" placeholder="Password" autocomplete="on">
            </div>

            <button type="submit" class="bg-black text-white w-full h-10">Confirm</button>
        </form>

        <div class="w-0 h-0">
        </div>
    </section>