    <!-- TEMPLATE CONNEXION -->
    <section class="flex flex-col items-center w-full h-fit gap-40 align-middle">

        <div class="flex bg-ligth-gray justify-between items-center w-full h-14 py-2">
            <div class="flex justify-center items-center w-6 h-6 ml-8">
                <img class="w-full h-full object-contain" src="../assets/arrow-left.svg" alt="Arrow Left">
            </div>
            <p class="text-sm font-normal">Sign in / Register</p>
            <div class="w-16 h-16"></div>
        </div>

        <div class="flex flex-col justify-center items-center w-full h-fit">
            <form id="connection" class="flex flex-col gap-4 w-25rem h-fit">

                <div class="flex flex-col w-25rem h-fit">
                    <p class="text-xs text-gray">Please enter your Email Address</p>
                    <input class="required:border-red-500 border-2 border-gray p-2" type="email" placeholder="Email" autocomplete="on" name="mail">    </div>

                <button  type="submit" class="bg-black text-white w-full h-10">Continue</button>
            </form>
        </div>

        <div class="w-0 h-0">
        </div>
    </section>
