    <section class="w-full h-fit justify-center items-center">
        <div class="relative w-full h-fit inset-0 flex justify-center items-center bg-yellow text-dark text-xs font-normal py-2" id="overlay-text">
                Use code MADE10 for a 10% discount on your next purchase. Limited time offer.
        </div>

        <div class="relative w-full h-full">

            <video class="w-full h-full" src="../assets/bgVideoAccueil.mp4" preload="auto" muted autoplay loop></video>

            <div
                class="absolute left-1/2 transform -translate-x-1/2 bottom-10 w-fit h-fit flex justify-center items-center text-white border-b-2 border-b-white">
                <a href="#">Shop all Bedroom</a>
            </div>

        </div>

    </section>