<div class="flex flex-col items-center gap-1 max-w-40 w-fit h-fit"></div>
    <p class="text-sm text-right font-medium max-w-full" data-id="user-name">Welcome, {{firstname}}</p>
    <a id="logout" data-id="logout" title="Se déconnecter" href="#" class="w-fit h-fit flex justify-end gap-1">
        <img data-id="logout" src="../assets/akar-icons_door.svg" alt="Disconnect"  class="w-6 h-6 ">
    </a>
</div>