<article id="card" data-id="{{id}}" class="flex flex-col gap-4 w-fit maw-h-30rem m-4 items-stretch cursor-pointer" data-id="{{id}}">
    <div class="w-64 h-80 flex items-center justify-center" data-id="{{id}}">
        <img class="bg-cover" src="{{image}}" alt="Image du produit : {{name}}" data-id="{{id}}">
    </div>
    <div class="flex flex-row justify-between" data-id="{{id}}">
        <p data-id="{{id}}">£{{price}}</p>
        <img class="w-6 h-6" src="../assets/heart.png" data-id="{{id}}">
    </div>
    <p class="w-64 h-12" data-id="{{id}}">{{name}}</p>
</article>
