    <footer class="flex flex-col justify-center items-center bg-ligth-gray">
        <div class="flex flex-row gap-5 text-sm justify-items-stretch">
            <!--  -->
            <ul class="flex flex-col gap-5 p-8 list-none">
                <li>
                    <h2 class="">HOW CAN WE HELP</h2>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Frequently
                        Asked Questions</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Contact Us</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Track My
                        Order</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Delivery</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Arrange a
                        Return</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Inspiration</a>
                </li>
            </ul>

            <!--  -->
            <ul class="flex flex-col gap-5 p-8 list-none">
                <li>
                    <h2 class="">ABOUT US</h2>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">About MADE</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Terms &
                        Conditions</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Manually Manage
                        Cookies</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Cookies &
                        Privacy</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Modern Slavery
                        Statement</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Gender Pay
                        Report</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Corporate
                        Responsibility Report</a>
                </li>
            </ul>

            <!--  -->
            <ul class="flex flex-col gap-5 p-8 list-none">
                <li>
                    <h2 class="">SHOP BY DEPARTEMENT</h2>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Living Room</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Dining Room</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Bedroom</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Garden</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Furniture</a>
                </li>
                <li>
                    <a href="#" class="hover:border-b-black border-b-2 border-b-transparent ease-in-out">Lighting</a>
                </li>
            </ul>
        </div>

        <div class="w-full h-fit p-5 text-center font-light">
            <p class="font-DM font-medium">&copy; 2024 All rights reserved.</p>
        </div>
    </footer>