<footer>
    <div class="flex flex-row">
            <ul>
                <li><h2>HOW CAN WE HELP</h2></li>
                <li>Frequently Asked Questions</li>
                <li>Contact Us</li>
                <li>Track My Order</li>
                <li>Delivery</li>
                <li>Arrange a Return</li>
                <li>Inspiration</li>
            </ul>

            <ul>
                <li><h2>ABOUT US</h2></li>
                <li>About MADE</li>
                <li>Terms & Conditions</li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>

            <ul>
                <li><h2>SHOP BY DEPARTEMENT</h2></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
    </div>
    <p>&copy; 2024 All rights reserved.</p>
</footer>