<div class="flex flex-col gap-4 w-fit h-auto m-4 items-stretch cursor-pointer">
    <div class="w-64 h-80 flex items-center justify-center">
        <img src="{{image}}" alt="Image du produit : {{name}}">
    </div>
    <div class="flex flex-row justify-between">
        <p>£{{price}}</p>
        <img class="w-6 h-6" src="../assets/heart.png">
    </div>
    <p class="w-64 h-12">{{name}}</p>
</div> 
