<div class="flex flex-row gap-3 w-fit h-fit">
    <a href="#">
        <svg href="../../../../assets/made_my-account_desktop.svg" viewBox="0 0 24 24" fill="currentColor">
        </svg>
    </a>
    <a href="#">
        <svg href="../../../../assets/favourites-inactive-large.svg" viewBox="0 0 24 24" fill="currentColor">
        </svg>
    </a>
    <a href="#">
        <svg href="../../../../assets/shopping-bag-large.svg" viewBox="0 0 24 24" fill="currentColor">
        </svg>
    </a>

    <button class="hover:bg-black bg-gray text-white font-DM font-semibold p-3 h-fit w-fill">Checkout</button>
</div>
